### ISSUE TITLE
[ALL SITES] - Need to make embedded maps responsive

### ISSUE THREAD

**Issue by cheroma21** [distributedigital/issues#29]

**Comment by dstaley** [comment]
@cheroma21 how often are we doing this? It's basically the same problem with YouTube embeds. There isn't a magical solution to make it work.

**Comment by cheroma21** [comment]
225 embeds a shit ton of stuff. This is a CVP issue that requires a plugin solution for both

**Comment by dstaley** [comment]
grosssss
