### ISSUE TITLE
Updates to 225 OlaPic Page Header

### ISSUE THREAD

**Issue by JWOConnor** [distributedigital/issues#5]
Deadline: Before August 19th
(In time for fashion month contest and next event where we will be loading pictures here)

"Old" 225 header is on photos.225batonrouge.com and needs to be updated. Contains old links that are now invalid.

![screen shot 2013-07-24 at 11 29 03 am](https://f.cloud.github.com/assets/4852007/849973/36051788-f47e-11e2-8fab-2420a3cc30a9.png)

**Comment by dstaley** [comment]
@JWOConnor can you email me the login information for Olapic? IIRC, this is something we have to fix through their interface.

**Comment by JWOConnor** [comment]
@dstaley here you go:

225batonrouge@olpaic
rmccoll225
olapic.com
